<?php
declare(strict_types=1);

namespace ZealPHP\Tests\Unit;

use OpenSwoole\Core\Psr\Response;
use OpenSwoole\Core\Psr\ServerRequest;
use PHPUnit\Framework\Attributes\DataProvider;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Server\RequestHandlerInterface;
use ZealPHP\App;
use ZealPHP\Middleware\BasicAuthMiddleware;
use ZealPHP\RequestContext;
use ZealPHP\Tests\TestCase;

/**
 * Behavioural + algorithmic conformance for BasicAuthMiddleware (RFC 7617).
 *
 * The htpasswd hash vectors below are generated by INDEPENDENT oracles
 * (`openssl passwd`, perl `crypt`, PHP `password_hash`) — not by the class
 * under test — so they pin the APR1 / SHA-1 / crypt reimplementations against
 * a third party. Any arithmetic drift in crypt_apr1_md5() produces a different
 * digest, the hash_equals() check fails, and the corresponding test flips to
 * 401 — which is exactly how the APR1 loop mutants get caught.
 */
class BasicAuthMiddlewareTest extends TestCase
{
    /** openssl passwd -apr1 -salt Zx9KpQ2m <pass> — keyed by password (varied lengths). */
    private const APR1 = [
        'x'                    => '$apr1$Zx9KpQ2m$VguUsQdoEzgRxNC/JcCF7/',
        'secret'               => '$apr1$Zx9KpQ2m$cOS6B0aNCSNQrim1HeIwo/',
        '0123456789abcdef'     => '$apr1$Zx9KpQ2m$5NEKivtq581GEpaVPpATH0',
        '0123456789abcdefg'    => '$apr1$Zx9KpQ2m$264OBKnd5OoAL.Kshvdc4/',
        '0123456789abcdefghij' => '$apr1$Zx9KpQ2m$NjaM7xxrNgXCFm0phDGIi0',
    ];
    private const BCRYPT = '$2y$04$ne9j7VwgZQHvr2GwGk4A6.ZKRVWsrywZTHJ8pBF98YOvNUiGMjvJe'; // secret
    private const SHA1   = '{SHA}5en6G6MezRroT3XKqkdPOmY/BfQ=';                            // secret
    private const SHA512 = '$6$abcdefgh$ltjgWl6579NluT/Vi1nwEvcil.G5Nbc4NiXZaNGStk8PSwGfQv72N2CKPPrVACtLtip/cZ/1GM/O6IND4WQhG.'; // secret
    private const DES    = 'abNANd1rDfiNc';                                                // crypt("secret","ab")

    /** @var list<string> */
    private array $tmpFiles = [];

    protected function setUp(): void
    {
        App::$cwd = ZEALPHP_ROOT;
        App::superglobals(true);
    }

    protected function tearDown(): void
    {
        foreach ($this->tmpFiles as $f) {
            @unlink($f);
        }
        $this->tmpFiles = [];
    }

    // ----- construction -------------------------------------------------

    public function testConstructorThrowsWhenNeitherFileNorVerify(): void
    {
        $this->expectException(\InvalidArgumentException::class);
        new BasicAuthMiddleware();
    }

    public function testConstructorAcceptsFileOnly(): void
    {
        $mw = new BasicAuthMiddleware(htpasswdFile: $this->writeHtpasswd("u:" . self::BCRYPT));
        $this->assertInstanceOf(BasicAuthMiddleware::class, $mw);
    }

    public function testConstructorAcceptsVerifyOnly(): void
    {
        $mw = new BasicAuthMiddleware(verify: fn(string $u, string $p): bool => true);
        $this->assertInstanceOf(BasicAuthMiddleware::class, $mw);
    }

    // ----- challenge (401) shape ---------------------------------------

    public function testMissingAuthorizationChallenges(): void
    {
        $resp = $this->invoke(verify: fn() => true, authHeader: null);
        $this->assertSame(401, $resp->getStatusCode());
        $this->assertSame('Unauthorized', (string)$resp->getBody());
        $this->assertSame('text/plain', $resp->getHeaderLine('Content-Type'));
        $this->assertSame('Basic realm="Restricted"', $resp->getHeaderLine('WWW-Authenticate'));
    }

    public function testRealmAppearsInChallenge(): void
    {
        $resp = $this->invoke(verify: fn() => true, authHeader: null, realm: 'Admin Area');
        $this->assertSame('Basic realm="Admin Area"', $resp->getHeaderLine('WWW-Authenticate'));
    }

    public function testRealmQuotesAreEscaped(): void
    {
        $resp = $this->invoke(verify: fn() => true, authHeader: null, realm: 'a"b');
        $this->assertSame('Basic realm="a\\"b"', $resp->getHeaderLine('WWW-Authenticate'));
    }

    // ----- Authorization header parsing --------------------------------

    public function testValidCredentialsPassThrough(): void
    {
        $resp = $this->invoke(verify: fn() => true, authHeader: $this->basic('user', 'pass'));
        $this->assertSame(200, $resp->getStatusCode());
        $this->assertSame('OK', (string)$resp->getBody());
    }

    public function testVerifyReceivesExactUserAndPass(): void
    {
        $seen = [];
        $verify = function (string $u, string $p) use (&$seen): bool {
            $seen = [$u, $p];
            return true;
        };
        $this->invoke(verify: $verify, authHeader: $this->basic('alice', 's3:cret'));
        // explode(':', $decoded, 2) — password keeps its embedded colon.
        $this->assertSame(['alice', 's3:cret'], $seen);
    }

    public function testVerifyRejectionChallenges(): void
    {
        $resp = $this->invoke(verify: fn() => false, authHeader: $this->basic('user', 'pass'));
        $this->assertSame(401, $resp->getStatusCode());
    }

    public function testCaseInsensitiveScheme(): void
    {
        $resp = $this->invoke(verify: fn() => true, authHeader: 'basic ' . base64_encode('user:pass'));
        $this->assertSame(200, $resp->getStatusCode());
    }

    public function testTrailingWhitespaceTolerated(): void
    {
        $resp = $this->invoke(verify: fn() => true, authHeader: 'Basic ' . base64_encode('user:pass') . '   ');
        $this->assertSame(200, $resp->getStatusCode());
    }

    public function testWrongSchemeChallenges(): void
    {
        $resp = $this->invoke(verify: fn() => true, authHeader: 'Bearer ' . base64_encode('user:pass'));
        $this->assertSame(401, $resp->getStatusCode());
    }

    public function testCaretAnchorRejectsPrefixedScheme(): void
    {
        // `^Basic` requires the scheme at the very start — "xBasic …" must fail.
        $resp = $this->invoke(verify: fn() => true, authHeader: 'xBasic ' . base64_encode('user:pass'));
        $this->assertSame(401, $resp->getStatusCode());
    }

    public function testDollarAnchorRejectsTrailingJunk(): void
    {
        // `\s*$` anchors the end — non-whitespace after the token must fail.
        $resp = $this->invoke(verify: fn() => true, authHeader: 'Basic ' . base64_encode('user:pass') . ' junk');
        $this->assertSame(401, $resp->getStatusCode());
    }

    public function testStatusIsSetTo401OnRequestContext(): void
    {
        $this->invoke(verify: fn() => true, authHeader: null);
        $this->assertSame(401, RequestContext::instance()->status);
    }

    public function testWwwAuthenticateWrittenToRawResponse(): void
    {
        // challenge() writes WWW-Authenticate onto the raw OpenSwoole response
        // when one is present (the path that propagates the header on the wire).
        $captured = [];
        $fake = new class($captured) {
            /** @param array<string,string> $sink */
            public function __construct(public array &$sink) {}
            public function header(string $name, string $value): void
            {
                $this->sink[$name] = $value;
            }
        };
        RequestContext::instance()->zealphp_response = $fake;

        $this->invoke(verify: fn() => true, authHeader: null, realm: 'Secure');

        RequestContext::instance()->zealphp_response = null;
        $this->assertSame('Basic realm="Secure"', $captured['WWW-Authenticate'] ?? null);
    }

    public function testInvalidBase64Challenges(): void
    {
        $resp = $this->invoke(verify: fn() => true, authHeader: 'Basic !!!notbase64!!!');
        $this->assertSame(401, $resp->getStatusCode());
    }

    public function testDecodedWithoutColonChallenges(): void
    {
        $resp = $this->invoke(verify: fn() => true, authHeader: 'Basic ' . base64_encode('nocolonhere'));
        $this->assertSame(401, $resp->getStatusCode());
    }

    public function testEmptyUserChallenges(): void
    {
        $resp = $this->invoke(verify: fn() => true, authHeader: 'Basic ' . base64_encode(':passonly'));
        $this->assertSame(401, $resp->getStatusCode());
    }

    public function testEmptyHeaderChallenges(): void
    {
        $resp = $this->invoke(verify: fn() => true, authHeader: '');
        $this->assertSame(401, $resp->getStatusCode());
    }

    // ----- htpasswd hash formats (independent oracle vectors) ----------

    public function testBcryptCorrectPassword(): void
    {
        $this->assertSame(200, $this->htpasswdAuth('u:' . self::BCRYPT, 'u', 'secret'));
    }

    public function testBcryptWrongPassword(): void
    {
        $this->assertSame(401, $this->htpasswdAuth('u:' . self::BCRYPT, 'u', 'nope'));
    }

    public function testSha1CorrectPassword(): void
    {
        $this->assertSame(200, $this->htpasswdAuth('u:' . self::SHA1, 'u', 'secret'));
    }

    public function testSha1WrongPassword(): void
    {
        $this->assertSame(401, $this->htpasswdAuth('u:' . self::SHA1, 'u', 'Secret'));
    }

    public function testSha512CryptCorrectPassword(): void
    {
        $this->assertSame(200, $this->htpasswdAuth('u:' . self::SHA512, 'u', 'secret'));
    }

    public function testSha512CryptWrongPassword(): void
    {
        $this->assertSame(401, $this->htpasswdAuth('u:' . self::SHA512, 'u', 'wrong'));
    }

    public function testDesCryptCorrectPassword(): void
    {
        $this->assertSame(200, $this->htpasswdAuth('u:' . self::DES, 'u', 'secret'));
    }

    public function testDesCryptWrongPassword(): void
    {
        $this->assertSame(401, $this->htpasswdAuth('u:' . self::DES, 'u', 'secre'));
    }

    // ----- M13: explicit plaintext rejection ----------------------------

    /**
     * A no-prefix plaintext entry (htpasswd -p / ALG_PLAIN) must be refused
     * deterministically — not accidentally via crypt() misbehaviour.
     * The password "hunter2" stored as literal "hunter2" in the file must
     * never authenticate, regardless of crypt() behaviour on this platform.
     */
    public function testPlaintextEntryIsRejectedExplicitly(): void
    {
        // Entry has no recognised hash prefix — it IS the plaintext password.
        $this->assertSame(401, $this->htpasswdAuth('u:hunter2', 'u', 'hunter2'));
    }

    public function testPlaintextEntryIsRejectedForWrongPassword(): void
    {
        $this->assertSame(401, $this->htpasswdAuth('u:hunter2', 'u', 'wrong'));
    }

    /**
     * Recognised schemes must still pass through to their verifier after the
     * plaintext guard — the guard must not over-block.
     */
    public function testBcryptPrefixPassesPlaintextGuard(): void
    {
        $this->assertSame(200, $this->htpasswdAuth('u:' . self::BCRYPT, 'u', 'secret'));
    }

    public function testApr1PrefixPassesPlaintextGuard(): void
    {
        $this->assertSame(200, $this->htpasswdAuth('u:' . self::APR1['secret'], 'u', 'secret'));
    }

    public function testSha1PrefixPassesPlaintextGuard(): void
    {
        $this->assertSame(200, $this->htpasswdAuth('u:' . self::SHA1, 'u', 'secret'));
    }

    // ----- L3: DES crypt 8-character truncation pin ---------------------

    /**
     * DES crypt silently truncates passwords to 8 characters.
     * This test pins the current behaviour: a password whose first 8 chars
     * match the DES hash authenticates even if the full password is longer.
     *
     * self::DES is crypt("secret", "ab") — the 6-char password "secret".
     * "secretXY" shares the first 6 chars but DES truncates at 8, so all of
     * "secretXY" (8 chars) are hashed against crypt("secretXY", "ab").
     * Since "secret" ≠ "secretXY" at the crypt() level, this must be 401.
     */
    public function testDesCryptEightCharTruncationPin(): void
    {
        // DES hash for "secret" (6 chars). "secret12" differs beyond char 6
        // but DES truncation only affects passwords > 8 chars.
        // Confirm the 6-char password matches, and a 9-char variant does not.
        $this->assertSame(200, $this->htpasswdAuth('u:' . self::DES, 'u', 'secret'));

        // "secret" + 3 extra chars — crypt() sees all 9 chars, but DES only
        // uses the first 8, so "secretXYZ" is hashed as "secretXY".
        // crypt("secretXYZ", "ab") == crypt("secretXY", "ab") ≠ crypt("secret", "ab").
        $this->assertSame(401, $this->htpasswdAuth('u:' . self::DES, 'u', 'secretXYZ'));

        // Construct a DES hash for "abcdefgh" (exactly 8 chars) and verify
        // that "abcdefghIJK" (11 chars) authenticates as the same 8-char block.
        $des8 = crypt('abcdefgh', 'ab');
        $this->assertSame(200, $this->htpasswdAuth('u:' . $des8, 'u', 'abcdefgh'));
        // First 8 chars identical — DES truncates to the same 8, so 401 would
        // mean DES truncation is broken; 200 confirms it is silently happening.
        $this->assertSame(200, $this->htpasswdAuth('u:' . $des8, 'u', 'abcdefghIJK'));
    }

    // ----- L2: bcrypt result cache — SKIP NOTE --------------------------
    // Apache caches the last bcrypt result in r->connection->notes (util.c:3520).
    // This per-connection cache is NOT implemented here: storing a (hash, result)
    // pair safely across requests in the coroutine model would require
    // coroutine-context storage (OpenSwoole\Coroutine::getContext()), but the
    // connection spans multiple coroutines on a keep-alive connection. A naive
    // static/instance cache would race across concurrent requests and risk
    // serving a stale hit to the wrong user. The perf cost (~100 ms per
    // bcrypt at cost=10) is accepted over the correctness risk.

    public function testUnknownUserChallenges(): void
    {
        $this->assertSame(401, $this->htpasswdAuth('u:' . self::BCRYPT, 'ghost', 'secret'));
    }

    /**
     * APR1 across password lengths 1 / 6 / 16 / 17 / 20 — exercises every
     * length-dependent loop in crypt_apr1_md5(). Correct password must match
     * the openssl-generated digest exactly; mutated arithmetic cannot.
     */
    #[DataProvider('apr1Provider')]
    public function testApr1CorrectPassword(string $password, string $hash): void
    {
        $this->assertSame(200, $this->htpasswdAuth('u:' . $hash, 'u', $password));
    }

    #[DataProvider('apr1Provider')]
    public function testApr1WrongPassword(string $password, string $hash): void
    {
        $this->assertSame(401, $this->htpasswdAuth('u:' . $hash, 'u', $password . 'X'));
    }

    /** @return iterable<string, array{string, string}> */
    public static function apr1Provider(): iterable
    {
        foreach (self::APR1 as $password => $hash) {
            yield $password => [$password, $hash];
        }
    }

    // ----- htpasswd file parsing ---------------------------------------

    public function testFileMissingChallenges(): void
    {
        $mw = new BasicAuthMiddleware(htpasswdFile: '/nonexistent/zealphp/htpasswd-' . uniqid());
        $resp = $mw->process($this->request($this->basic('u', 'secret')), $this->okHandler());
        $this->assertSame(401, $resp->getStatusCode());
    }

    public function testCommentsBlankLinesAndMalformedLinesSkipped(): void
    {
        $contents = implode("\n", [
            '# a comment',
            '',
            'noColonLineIsSkipped',
            '   ',
            ':emptyUserSkipped',
            'emptyHashSkipped:',
            'u:' . self::BCRYPT,
        ]);
        $this->assertSame(200, $this->htpasswdAuth($contents, 'u', 'secret'));
    }

    public function testUserAndHashAreTrimmed(): void
    {
        // surrounding whitespace on both fields must be stripped
        $this->assertSame(200, $this->htpasswdAuth("  u  :  " . self::BCRYPT . "  ", 'u', 'secret'));
    }

    public function testEmptyUserLineDoesNotAuthenticate(): void
    {
        // a line that is ONLY ":hash" must not register an empty-username entry
        $resp = $this->invoke(
            verify: null,
            authHeader: $this->basic('', 'secret'),
            file: ':' . self::BCRYPT,
        );
        $this->assertSame(401, $resp->getStatusCode());
    }

    public function testCacheRereadsAfterMtimeChange(): void
    {
        $file = $this->writeHtpasswd('alice:' . self::BCRYPT);
        $mw = new BasicAuthMiddleware(htpasswdFile: $file);

        // First call populates the cache and authenticates alice.
        $r1 = $mw->process($this->request($this->basic('alice', 'secret')), $this->okHandler());
        $this->assertSame(200, $r1->getStatusCode(), 'alice should authenticate from initial file');

        // bob is unknown yet → 401 (proves the cache holds only alice).
        $r2 = $mw->process($this->request($this->basic('bob', 'secret')), $this->okHandler());
        $this->assertSame(401, $r2->getStatusCode());

        // Rewrite with bob and bump mtime forward so the cache is invalidated.
        $mtime = (int)filemtime($file);
        file_put_contents($file, 'bob:' . self::BCRYPT . "\n");
        touch($file, $mtime + 10);
        clearstatcache(true, $file);

        $r3 = $mw->process($this->request($this->basic('bob', 'secret')), $this->okHandler());
        $this->assertSame(200, $r3->getStatusCode(), 'bob should authenticate after mtime-changed reload');
    }

    public function testStaleCacheServedWhenMtimeUnchanged(): void
    {
        // The mtime guard (htpasswdMtime === $mtime) means an edit that does
        // NOT advance mtime is intentionally served from the stale cache.
        // This pins the cache-key identity check: drop it and the rewrite
        // would be picked up, flipping bob to 200.
        $file = $this->writeHtpasswd('alice:' . self::BCRYPT);
        $mw = new BasicAuthMiddleware(htpasswdFile: $file);

        $r1 = $mw->process($this->request($this->basic('alice', 'secret')), $this->okHandler());
        $this->assertSame(200, $r1->getStatusCode());

        $mtime = (int)filemtime($file);
        file_put_contents($file, 'bob:' . self::BCRYPT . "\n");
        touch($file, $mtime); // keep mtime identical → cache must NOT reload
        clearstatcache(true, $file);

        $r2 = $mw->process($this->request($this->basic('bob', 'secret')), $this->okHandler());
        $this->assertSame(401, $r2->getStatusCode(), 'bob must NOT authenticate from stale cache');
    }

    public function testCachedHitReusesParsedMap(): void
    {
        // Two successive calls with an unchanged file both succeed — the second
        // travels the cache-hit branch (htpasswdCache !== null && mtime ===).
        $file = $this->writeHtpasswd('alice:' . self::BCRYPT);
        $mw = new BasicAuthMiddleware(htpasswdFile: $file);
        $a = $mw->process($this->request($this->basic('alice', 'secret')), $this->okHandler());
        $b = $mw->process($this->request($this->basic('alice', 'secret')), $this->okHandler());
        $this->assertSame(200, $a->getStatusCode());
        $this->assertSame(200, $b->getStatusCode());
    }

    // ----- helpers ------------------------------------------------------

    private function basic(string $user, string $pass): string
    {
        return 'Basic ' . base64_encode($user . ':' . $pass);
    }

    private function request(?string $authHeader): ServerRequestInterface
    {
        $headers = $authHeader === null ? [] : ['authorization' => $authHeader];
        return new ServerRequest('/', 'GET', '', $headers);
    }

    private function okHandler(): RequestHandlerInterface
    {
        return new class implements RequestHandlerInterface {
            public function handle(ServerRequestInterface $request): ResponseInterface
            {
                return new Response('OK', 200, '', ['Content-Type' => 'text/plain']);
            }
        };
    }

    /**
     * Run the middleware with a verify callback and/or an htpasswd file.
     */
    private function invoke(
        ?callable $verify = null,
        ?string $authHeader = null,
        string $realm = 'Restricted',
        ?string $file = null,
    ): ResponseInterface {
        $path = $file === null ? null : $this->writeHtpasswd($file);
        $mw = new BasicAuthMiddleware(
            htpasswdFile: $path,
            verify: $verify,
            realm: $realm,
        );
        return $mw->process($this->request($authHeader), $this->okHandler());
    }

    /**
     * Authenticate $user/$pass against an htpasswd file whose contents are
     * $fileContents; returns the resulting HTTP status code.
     */
    private function htpasswdAuth(string $fileContents, string $user, string $pass): int
    {
        $mw = new BasicAuthMiddleware(htpasswdFile: $this->writeHtpasswd($fileContents));
        return $mw->process($this->request($this->basic($user, $pass)), $this->okHandler())
            ->getStatusCode();
    }

    private function writeHtpasswd(string $contents): string
    {
        $path = tempnam(sys_get_temp_dir(), 'zphp-htpasswd-');
        if ($path === false) {
            $this->fail('could not create temp htpasswd file');
        }
        file_put_contents($path, $contents . "\n");
        $this->tmpFiles[] = $path;
        return $path;
    }
}
